---
title: "**Lectures**"
author: "RJ Dyer"
date: "Center for Environmental Studies"
output:
  html_document:
    css: ["https://www.w3schools.com/w3css/4/w3.css", "index_style.css"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(purrr)
library(stringr)
library(tidyverse)
```

Below are all the lecture topics that I've developed for various classes taught at the [Center for Environmental Studies](https://ces.vcu.edu).  For more information on these lectures, feel free to contact me directly at [rjdyer@vcu.edu](mailto://rjdyer@vcu.edu).


```{r echo=FALSE}

files <- list.dirs(recursive = FALSE)

video <- "<a href='https://www.youtube.com/watch?v=dQw4w9WgXcQ' class='w3-button w3-round-large w3-amber'>Video</a>"


btn <- function(path, color, name, as.nb=FALSE) {
  nb <- ifelse( as.nb, ".nb", "")
  code <- paste( "<a href='", 
                 path, "/",name, nb,
                 ".html' class='w3-button w3-round-large w3-", 
                 color, "'>", Hmisc::capitalize(name),"</a>",
                 sep="")
  return( code )
}

video <- function( path, color, name ) {
  val <- read_file(  paste(path,"video.txt",sep="/") )
  btn <- paste("<a href='",
               val,
               "' class='w3-button w3-round-large w3-", 
                 color, "'>",Hmisc::capitalize(name),"</a>", sep="")
  return(btn)
}


titles <- unlist( map( str_replace( str_replace_all(files,"_", " "), "./", "" ),
                       gtools::capwords ) )



buttons <- numeric(0)
for( path in files ) {

  vid <- ifelse( file.exists(  paste(path,"video.txt", sep="/") ),
                   video( path, "amber", "video"), "")

  slides <- ifelse( file.exists(  paste(path,"slides.Rmd", sep="/") ),
                    btn(path,"orange","slides"),
                    "")
  
  narriative <- ifelse( file.exists(  paste(path,"narriative.Rmd", sep="/") ),
                    btn(path,"blue","narriative",as.nb = TRUE),
                    "")

##  tutorial <- ifelse( file.exists(  paste(path,"tutorial/tutorial.Rmd", sep="/") ),
#3                    btn(path,"blue","tutorial"),
##                    "")

  
  homework <- ifelse( file.exists(  paste(path,"homework.Rmd", sep="/") ),
                    btn(path,"indigo","homework", as.nb=TRUE),
                    "")

  buttons <- c(buttons, 
               paste(vid,slides,narriative, homework))

}

df <- data.frame( Topic=titles,
                  Connections = buttons
                 )


# fix a few special cases
df$Topic[ which( df$Topic == "Ggplot") ] <- "GGPlot2"

df %>%
  knitr::kable(format="html", 
               escape=FALSE, 
               caption = "HTML lecture slides and homework for selected topics.") %>%
  kableExtra::kable_styling( bootstrap_options = c("striped", 
                                                   "hover", 
                                                   "condensed", 
                                                   "responsive"),
                             full_width = FALSE,
                             position = "left",
                             fixed_thead = T)

```

<hr>

This file last updated: `r date()`.