---
title: "Leaflet Homework"
author: "YOUR NAME HERE"
date: "3/15/2021"
output: html_notebook
---

## Cartography/Leaflet Homework

Create a map similar to [this map from the Washington Post](https://www.washingtonpost.com/sf/local/2013/11/09/washington-a-world-apart/) (open the link in an incognito window to avoid the paywall if you need) for Richmond using the educational attainment data linked below and census tracts that you will download with the `tigris` package

```{r eval=FALSE}
library( sf )

# Download the tigris package if necessary
if( !require( tigris) ) {
  install.packages("tigris")
  library( tigris)
}

education_url <- "https://github.com/dyerlab/ENVS-Lectures/raw/master/data/edu_attainment-shp.zip"

tracts <- tracts("VA", "Richmond city") %>%
  st_transform(4326)

```


### Map Requirements

- Dot density map of education attainment when zoomed out, with dot color based on attainment level

- Choropleth map of education attainment level by census tracts when zoomed in
  
  - [`pivot_wider()`](https://cran.r-project.org/web/packages/tidyr/vignettes/pivot.html) and [`tally()`](https://dplyr.tidyverse.org/reference/tally.html) were helpful for me to combine the point data and the tracts polygons

- Legend

- Scale bar

- At least one feature with a pop-up or label


---

If you get stuck transforming the education attainment data from points to polygons you can download [this csv](https://github.com/dyerlab/ENVS-Lectures/raw/master/data/edu_tally.csv). It is a tally of the number of points per tract by education attainment. It is up to you what metric to use to color the polygons.


 