---
title: "$\\LaTeX$ in Markdown"
output: html_notebook
---

The ability to typeset numerial and mathematical symbols is key to scientific writing.  In the old days (old-man Dyer shaking his fist at kids on the lawn), a system was defined for this called $\TeX$ and then a refined version was created and called $\LaTeX$.  In RMarkdown, we can use $\LaTeX$ components within our markdown documents to represent 


## Using $\LaTeX$

You can insert $\LaTeX$ into your markdown document as either in-line (e.g., within the text like in-line `R` code) as well as on its own line (as you would to represent an equation).

## Inline 

Symbols and operators in $\LaTeX$ generally start with a slash `\` immediately followed by the name of the function or operator.  In fact, the funny $\LaTeX$ name is denoted as `\LaTeX`.  To get Markdown to recognize these as $\LaTeX$ symbology and have it typeset in HTML or as a word doc or pdf, you **must** surround the $\LaTeX$ components with a dollar sign (`$`) on each end.  For example, if you want to typeset the square root of 23 as mathematical symbology, you would use `$\sqrt{23}$` and it would look like $\sqrt{23}$.

<div style="background-color:#fef5c4;	border:1px solid #fadf98; padding:5px;">Notice that the arguments that you pass to the $\LaTeX$ command (`\sqrt` here) are *curly brackets*, not parentheses.  For `R`, function paramters are enclosed in parentheses, in $\LaTeX$ they are in curly brackets.</div>



## Individual Symbols

What follows are some basic letters and symbols for variables in your text.  

### Greek Letters

By far, Greek letters are most commonly used to represent variables in scientific writing.  

#### Lower Case


Symbol | Command | Symbol | Command | Symbol | Command  | Symbol | Command    
-------|---------|--------|---------|--------|----------|--------|----------  
$\alpha$ | `\alpha` | $\beta$ | `\beta` | $\gamma$ | `\gamma` | $\delta$ | `\delta`  
$\epsilon$ | `\epsilon` | $\varepsilon$ | `\varepsilon` | $\zeta$ | `\zeta` | $\eta$ | `\eta`  
$\theta$ | `\theta` | $\vartheta$ | `\vartheta` | $\iota$ | `\iota` | $\kappa$ | `\kappa`  
$\lambda$ | `\lambda` | $\mu$ | `\mu` | $\nu$ | `\nu` | $\xi$ | `\xi`  
$\pi$ | `\pi` | $\varpi$ | `\varpi` | $\rho$ | `\rho` | $\varrho$ | `\varrho`  
$\sigma$ | `\sigma` | $\varsigma$ | `\varsigma` | $\tau$ | `\tau` | $\upsilon$ | `\upsilon`  
$\phi$ | `\phi` | $\varphi$ | `\varphi` | $\chi$ | `\chi` | $\psi$ | `\psi`  
$\omega$ | `\omega` |  |  |  |  |  |   


#### Upper Case

Symbol | Command | Symbol | Command | Symbol | Command  | Symbol | Command    
-------|---------|--------|---------|--------|----------|--------|----------
$\Gamma$ | `\Gamma` | $\Delta$ | `\Delta` | $\Theta$ | `\Theta` | $\Lambda$ | `\Lambda`
$\Xi$ | `\Xi` | $\Pi$ | `\Pi` | $\Sigma$ | `\Sigma` | $\Upsilon$ | `\Upsilon`
$\Phi$ | `\Phi` | $\Psi$ | `\Psi` | $\Omega$ | `\Omega` |  | ``



#### Accents on Letters and Symbols

Symbol | Command | Symbol | Command | Symbol | Command
-------|---------|--------|---------|--------|----------
$\hat{x}$ | `\hat{x}` | $\check{x}$ | `\check{x}` | $\dot{x}$ | `\dot{x}`
$\breve{x}$ | `\breve{x}` | $\acute{x}$ | `\acute{x}` | $\ddot{x}$ | `\ddot{x}`
$\grave{x}$ | `\grave{x}` | $\tilde{x}$ | `\tilde{x}` | $\mathring{x}$ | `\mathring{x}`
$\bar{x}$ | `\bar{x}` | $\vec{x}$ | `\vec{x}` |  |  


#### Subscripts and Superscripts

Symbol | Command | Symbol | Command
-------|---------|--------|---------
$2^{2}$ | `2^2` | $\textstyle a_i$ | `a_i`
$\textstyle 2^{23}$ | `2^{23}` | $\textstyle n_{i-1}$ | `n_{i-1}`
$a^{i+1}_3$ | `a^{i+1}_3` | $x^{3^2}$ | `x^{3^2}`
$2^{a_i}$ | `2^{a_i}` | $2^a_i$ | `2^a_i`


### Mathematical Operators

The following are mathematical operators in $\LaTeX$. 

Symbol | Command | Symbol | Command | Symbol | Command
-------|---------|--------|---------|--------|----------
$\pm$ | `\pm` | $\mp$ | `\mp` | $\times$ | `\times`
$\div$ | `\div` | $\cdot$ | `\cdot` | $\ast$ | `\ast`
$\star$ | `\star` | $\dagger$ | `\dagger` | $\ddagger$ | `\ddagger`
$\amalg$ | `\amalg` | $\cap$ | `\cap` | $\cup$ | `\cup`
$\uplus$ | `\uplus` | $\sqcap$ | `\sqcap` | $\sqcup$ | `\sqcup`
$\vee$ | `\vee` | $\wedge$ | `\wedge` | $\oplus$ | `\oplus`
$\ominus$ | `\ominus` | $\otimes$ | `\otimes` | $\circ$ | `\circ`
$\bullet$ | `\bullet` | $\diamond$ | `\diamond` | $\lhd$ | `\lhd`
$\rhd$ | `\rhd` | $\unlhd$ | `\unlhd` | $\unrhd$ | `\unrhd`
$\oslash$ | `\oslash` | $\odot$ | `\odot` | $\bigcirc$ | `\bigcirc`
$\triangleleft$ | `\triangleleft` | $\Diamond$ | `\Diamond` | $\bigtriangleup$ | `\bigtriangleup`
$\bigtriangledown$ | `\bigtriangledown` | $\Box$ | `\Box` | $\triangleright$ | `\triangleright`
$\setminus$ | `\setminus` | $\wr$ | `\wr` | $\sqrt{x}$ | `\sqrt{x}`
$x^{\circ}$ | `x^{\circ}` | $\triangledown$ | `\triangledown` | $\sqrt[n]{x}$ | `\sqrt[n]{x}`
$a^x$ | `a^x` | $a^{xyz}$ | `a^{xyz}` | $a_x$ | `a_x`


### Mathematical Relations

Here are some relation symbols

Symbol | Command | Symbol | Command | Symbol | Command
-------|---------|--------|---------|--------|----------
$\le$ | `\le` | $\ge$ | `\ge` | $\neq$ | `\neq`
$\sim$ | `\sim` | $\ll$ | `\ll` | $\gg$ | `\gg`
$\doteq$ | `\doteq` | $\simeq$ | `\simeq` | $\subset$ | `\subset`
$\supset$ | `\supset` | $\approx$ | `\approx` | $\asymp$ | `\asymp`
$\subseteq$ | `\subseteq` | $\supseteq$ | `\supseteq` | $\cong$ | `\cong`
$\smile$ | `\smile` | $\sqsubset$ | `\sqsubset` | $\sqsupset$ | `\sqsupset`
$\equiv$ | `\equiv` | $\frown$ | `\frown` | $\sqsubseteq$ | `\sqsubseteq`
$\sqsupseteq$ | `\sqsupseteq` | $\propto$ | `\propto` | $\bowtie$ | `\bowtie`
$\in$ | `\in` | $\ni$ | `\ni` | $\prec$ | `\prec`
$\succ$ | `\succ` | $\vdash$ | `\vdash` | $\dashv$ | `\dashv`
$\preceq$ | `\preceq` | $\succeq$ | `\succeq` | $\models$ | `\models`
$\perp$ | `\perp` | $\parallel$ | `\parallel` | $\infty$ | `\infty`   
$\mid$ | `\mid` | $\bumpeq$ | `\bumpeq` | $\in$ |  `\in`  



### Functions

Symbol | Command | Symbol | Command
---------------|------------------|---------------|------------------
$\frac{1}{2}$     | `\frac{1}{2}` | $\sqrt{n}$ | `\sqrt{n}`  
$\sum_{i=1}^N x_i$ | `\sum_{i=1}^N x_i`  | $\prod_{i=1}^N x_i$ | `\prod_{i=1}^N x_i` 
$\lim_{x\to\infty}\frac{1}{x}$ | `\lim_{x\to\infty}\frac{1}{x}` | $\log_n n^2$ | `\log_n n^2`
$\left( x \right)$ | `\left( x \right)` | $\left[ x \right]$ | `\left[ x \right]`  






## $\LaTeX$ On Its Own Line

You can also have $\LaTeX$ as an element on its own line, say like an equation.  To do this, we need to have symbology before and after the line(s) that are to be typeset.  For this, we put two dollar signs on the row before the $\LaTeX$ and two after the line of $\LaTeX$.  

So, if you type the following three lines of code into your markdown document (for equation for the length of edges of an Euclidean triangle):

```
$$  
a^2 + b^2 = c^2  
$$
```

It will be visually depicted in the final document as.

$$
a^2 + b^2 = c^2
$$
You can also use square brackets instead of double dollar signs.  The output is identical.

\[
a^2 + b^2 = c^2
\]


### Matrices

Matrices must be put within an *array* field that has a beginning and end part.  The following code makes a $3x3$ matrix with square brackets on the left and right sides.

```
$$
\left[
\begin{array}{ccc}
a & b & c \\
d & e & f \\
g & h & i 
\end{array}
\right]
$$
```

The `\begin{array}{ccc}` and matching `\end{array}` components define a three column matrix.  The `{ccc}` indicates that the columns should be *c*entered in the ouptput.  Columns within the matrix are separated by the ampersand $&$.  There *must* be as many columns as indicated in the justification statement (e.g., the `{ccc}`).  Finally, the `\\` on the end of the the rows for the first two rows of the matric contents indicate a new line.  

Once typeset, it will look like the following matrix:

$$
\left[
\begin{array}{ccc}
a & b & c \\
d & e & f \\
g & h & i 
\end{array}
\right]
$$

## Wrapup

That should get you going for the time begin.  There is a whole world of $\LaTeX$ out there, but in the larger picture of everything, knowing you can use small components of it brings a lot of benefit to you.

---






